In [1]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import cm
import os
import statistics
import scipy.io
import h5py
import sys
import warnings
import seaborn as sns

warnings.filterwarnings('ignore')
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
from prepare_adjacency_matrix import GetData

In [3]:
FolderName = '/Users/seethakrishnan/Box Sync/NoReward/ImagingData/MultiDayData/Dataused/'

In [4]:
gd = GetData(FolderName, savefoldername='sigPF', placecellflag=True)

In [12]:
c = gd.get_adjacency_matrix(tasktocompare='Task2')

NR34
Number of pfs 133 Number of single pfs 115
25
Analysing..115 cells
Corr matrix min -0.7 and max 1.0
N edges: 2634
[1 2 3 4 5 6 7 8]
Nodes (115, 6)
CFC17
Number of pfs 184 Number of single pfs 157
22
Analysing..157 cells
Corr matrix min -0.6 and max 1.0
N edges: 4095
[1 2 3 4 5 6 7 8]
Nodes (157, 6)
NR32
Number of pfs 98 Number of single pfs 87
25
Analysing..87 cells
Corr matrix min -0.7 and max 1.0
N edges: 1394
[1 2 3 4 5 6 7 8]
Nodes (87, 6)
CFC16
Number of pfs 247 Number of single pfs 230
17
Analysing..230 cells
Corr matrix min -0.9 and max 1.0
N edges: 12446
[1 2 3 4 5 6 7 8]
Nodes (230, 6)
CFC18
Number of pfs 263 Number of single pfs 236
16
Analysing..236 cells
Corr matrix min -0.8 and max 1.0
N edges: 11478
[1 2 3 4 5 6 7 8]
Nodes (236, 6)


In [13]:
gd.get_adjacency_matrix(tasktocompare='Task4', basetask='Task3b')

NR34
Number of pfs 37 Number of single pfs 24
5
Analysing..24 cells
Corr matrix min -0.5 and max 0.8
N edges: 127
[1 2 3 4 5 7 8]
Nodes (24, 6)
CFC17
Number of pfs 186 Number of single pfs 142
15
Analysing..142 cells
Corr matrix min -0.7 and max 1.0
N edges: 3693
[1 2 3 4 5 6 7 8]
Nodes (142, 6)
NR32
Number of pfs 89 Number of single pfs 82
8
Analysing..82 cells
Corr matrix min -0.7 and max 0.9
N edges: 1642
[1 2 3 4 5 6 7 8]
Nodes (82, 6)
CFC16
Number of pfs 266 Number of single pfs 248
11
Analysing..248 cells
Corr matrix min -0.7 and max 0.9
N edges: 13942
[1 2 3 4 5 6 7 8]
Nodes (248, 6)
CFC18
Number of pfs 114 Number of single pfs 87
6
Analysing..87 cells
Corr matrix min -0.6 and max 0.8
N edges: 1755
[1 2 3 4 5 6 7 8]
Nodes (87, 6)


In [14]:
c = gd.get_adjacency_matrix(tasktocompare='Task1', basetask='Task1')

NR34
Number of pfs 133 Number of single pfs 115
25
Analysing..115 cells
Corr matrix min -0.8 and max 1.0
N edges: 3042
[1 2 3 4 5 6 7 8]
Nodes (115, 6)
CFC17
Number of pfs 184 Number of single pfs 157
22
Analysing..157 cells
Corr matrix min -0.6 and max 1.0
N edges: 4227
[1 2 3 4 5 6 7 8]
Nodes (157, 6)
NR32
Number of pfs 98 Number of single pfs 87
25
Analysing..87 cells
Corr matrix min -0.8 and max 1.0
N edges: 1831
[1 2 3 4 5 6 7 8]
Nodes (87, 6)
CFC16
Number of pfs 247 Number of single pfs 230
17
Analysing..230 cells
Corr matrix min -0.8 and max 1.0
N edges: 11750
[1 2 3 4 5 6 7 8]
Nodes (230, 6)
CFC18
Number of pfs 263 Number of single pfs 236
16
Analysing..236 cells
Corr matrix min -0.8 and max 1.0
N edges: 13196
[1 2 3 4 5 6 7 8]
Nodes (236, 6)


In [7]:
FolderName = '/Users/seethakrishnan/Box Sync/NoReward/ImagingData/MultiDayData/Remapping_Shuffle/'

In [13]:
gd = GetData(FolderName, savefoldername='Shuffle', placecellflag=True)
gd.get_adjacency_matrix(tasktocompare='Task4', basetask='Task1', shuffle_flag=False)

CFC4
Number of pfs 189 Number of single pfs 188
19
Analysing..188 cells
Corr matrix min -0.6 and max 0.8
N edges: 5786
[18.55632472]
[32.42359874]
[38.02372741]
[34.1610066]
[9.36330403]
[37.44523193]
[14.65001992]
[21.68970201]
[10.28369115]
[31.59455801]
[15.98023511]
[8.46438601]
[21.72892879]
[11.75090782]
[27.65427363]
[37.97295226]
[33.9336586]
[8.36416012]
[38.12129287]
[37.74341283]
[33.89608948]
[31.08602959]
[11.4065635]
[38.4732198]
[32.37416111]
[24.05813862]
[10.57981986]
[38.57195026]
[38.11087151]
[37.76776581]
[11.15011324]
[22.31145268]
[31.02721915]
[21.75670011]
[10.91007362]
[33.75705113]
[33.84068936]
[34.95706883]
[36.37940111]
[8.33029963]
[35.20394067]
[27.34309553]
[36.38599782]
[37.7857906]
[30.31243263]
[8.30333939]
[15.21130621]
[37.07305991]
[27.84559764]
[37.29555452]
[28.06868827]
[6.84982362]
[7.97635316]
[14.41596001]
[38.16994791]
[5.38884451]
[38.7957721]
[38.41556446]
[37.04985794]
[38.21154075]
[38.73537451]
[36.72392755]
[22.0921247]
[27.03313601]
